      $('.owl-carousel').owlCarousel({
    loop:true,
    margin:50,
    items:1,        
    nav:true,
    autoplay:true,
    autoplayTimeout:4000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
